export const HOME ='/';
export const SIGNIN="/signin";
export const SIGNUP="/signup";
export const SIGNOUT="/signout";
export const CANDIDATE_HOME = '/candidate/jobs';
export const CALL_CANDIDATE_BY_ADMIN = "/admin";
export const RECRUITER_HOME="/recruiter/jobs";
export const ALL_CANDIDATES="/admin/candidates";
export const ALL_RECRUITERS="/admin/recruiters";
export const ALL_JOBS="/admin/jobs";
export const AVAILABLE_JOBS="/candidate/jobs";
export const VIEW_APPLIED_JOBS="/candidate/jobs/applications";
export const ADMIN_DASHBOARD="/admin";
export const ADMIN_SIGNIN="/adminsignin";
export const RESET_PASSWORD="/resetpasswordsteps";
export const RECRUITER="/recruiter";
export const  APPLICANT_FOR_JOB_ROUTE="/recruiter/jobs/:jobId";
export const FORGOT_PASSWORD = "/forgetpassword";
export const RESET_PASWORD = '/resetpassword';
export const NO_MATCH = '/*'

